version: "{build}"

clone_depth: 10

environment:
  matrix:
    - nodejs_version: 4

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  - grunt test

cache:
  - node_modules

matrix:
  fast_finish: true
